apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "redash.adhocWorker.fullname" . }}
  labels:
    app: {{ template "redash.name" . }}
    component: adhocworker
    chart: {{ template "redash.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.adhocWorker.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "redash.name" . }}
      component: adhocworker
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "redash.name" . }}
        component: adhocworker
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "redash.name" . }}-adhocworker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["source /config/dynamicenv.sh && /app/bin/docker-entrypoint scheduler"]
          env:
            - name: REDASH_DATABASE_USER
              value: {{ $.Values.postgresql.postgresUser }}
            - name: REDASH_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "postgresql.secretName" . }}
                  key: postgres-password
            - name: REDASH_DATABASE_HOSTNAME
              value: {{ template "redash.postgresql.fullname" }}
            - name: REDASH_DATABASE_PORT
              value: {{ $.Values.postgresql.service.port }}
            - name: REDASH_DATABASE_DB
              value: {{ $.Values.postgresql.postgresDatabase }}
            - name: REDASH_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                {{- if .Values.redis.existingSecret }}
                  name: {{ .Values.redis.existingSecret }}
                {{- else }}
                  name: {{ template "redis.fullname" . }}
                {{- end }}
                  key: redis-password
            - name: REDASH_REDIS_HOSTNAME
              value: {{ template "redash.redis.fullname" }}
            - name: REDASH_REDIS_PORT
              value: {{ $.Values.redis.master.port }}
            - name: REDASH_REDIS_DB
              value: {{ $.Values.redis.databaseNumber }}
          {{- range $key, $value := .Values.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
          {{- end }}
          {{- range $key, $value := .Values.adhocWorker.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
          {{- end }}
          resources:
{{ toYaml .Values.adhocWorker.resources | indent 12 }}
    {{- if .Values.adhocWorker.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.adhocWorker.nodeSelector | indent 8 }}
    {{- end }}
    {{- with .Values.adhocWorker.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.adhocWorker.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
